#q10
# k=int(input("enter the number"))
# i=1
# sum=0
# f=[]
# while i<=k:
#     sum=sum+k%10
#     k=k//10
#     f.append(k)
# print(f)


# #10 
#  a=[[1,2,3],[5,8,9],[4,3,77,522,31,3111]]
#  i=0
# while i<len(a):
#     k=0
#     while k<len(a[i]):
#         print([a[i][k]])
#         k+=1
#     i+=1

# def h(a):
#     i=0
#     m=0
#     q=[]
#     while i<len(a):
#         j=0
#         l=len(a[i])
#         while j<l:
#             k=a[i][j]
#             if m<k:
#                 m=k
#             j+=1
#         i+=1
#         q.append(m)
#     print(q)
# h([[5,32,4,56],[32,33,67,89],[34,54,67,8],[98,90,43,32]])
